"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Alert, Box, Button, Container, Paper, TextField, Typography } from "@mui/material";

export default function AuthForm({ mode }: { mode: "login" | "signup" }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const signup = mode === "signup";
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`/api/auth/${signup ? "register" : "login"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(signup ? { name, email, password } : { email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push(data.user?.role === "ADMIN" ? "/admin" : "/"); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "Something went wrong."); } finally { setLoading(false); } }
  return <Box sx={{ minHeight: "calc(100vh - 150px)", bgcolor: "#111", py: 9 }}><Container maxWidth="sm"><Paper component="form" onSubmit={submit} sx={{ p: { xs: 3, sm: 5 }, bgcolor: "#1b1b1b", border: "1px solid #2b2b2b", borderRadius: 4 }}><Typography variant="h4" sx={{ color: "#fff", fontWeight: 700 }}>{signup ? "Create your account" : "Welcome back"}</Typography><Typography sx={{ color: "#a0a0a0", mt: 1, mb: 4 }}>{signup ? "Sign up to manage bookings and orders." : "Sign in to continue to Abhi Studio."}</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{signup && <TextField required label="Full name" value={name} onChange={(e) => setName(e.target.value)} fullWidth sx={{ mb: 2 }} />}<TextField required type="email" label="Email address" value={email} onChange={(e) => setEmail(e.target.value)} fullWidth sx={{ mb: 2 }} /><TextField required type="password" label="Password" helperText={signup ? "Use at least 8 characters." : undefined} value={password} onChange={(e) => setPassword(e.target.value)} fullWidth sx={{ mb: 3 }} /><Button type="submit" disabled={loading} fullWidth variant="contained" sx={{ bgcolor: "#FFD700", color: "#000", py: 1.4, fontWeight: 700, "&:hover": { bgcolor: "#e6c200" } }}>{loading ? "Please wait…" : signup ? "Create account" : "Sign in"}</Button><Typography sx={{ color: "#a0a0a0", textAlign: "center", mt: 3 }}>{signup ? "Already have an account? " : "New to Abhi Studio? "}<Link href={signup ? "/login" : "/signup"} style={{ color: "#FFD700" }}>{signup ? "Sign in" : "Create an account"}</Link></Typography></Paper></Container></Box>;
}
